# Generated by Django 4.2.5 on 2023-09-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_client_log_mailing_message_delete_customers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('ok', 'Исполнена'), ('failed', 'Провалена')], max_length=6, verbose_name='Статус попытки'),
        ),
    ]
