# Generated by Django 4.2.5 on 2023-09-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_log_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('success', 'Исполнена'), ('failed', 'Провалена')], max_length=7, verbose_name='Статус попытки'),
        ),
    ]
