# Generated by Django 4.2.4 on 2023-08-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_message_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Тема Сообщения'),
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commence_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала рассылки')),
                ('completion_time', models.DateTimeField(verbose_name='Время окончания рассылки')),
                ('frequency', models.CharField(choices=[('daily', 'ежедневно'), ('weekly', 'еженедельно'), ('monthly', 'ежемесячно')], default='daily', verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('completed', 'завершено'), ('created', 'создано'), ('commenced', 'запущено')], default='created', verbose_name='Статус расссылки')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.customer', verbose_name='Клиенты')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Письма')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
