# Generated by Django 4.2.4 on 2023-08-18 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_message_subject_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='customer',
        ),
        migrations.AlterField(
            model_name='sender',
            name='message',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Письма'),
        ),
        migrations.AddField(
            model_name='sender',
            name='customer',
            field=models.ManyToManyField(to='mailing.customer', verbose_name='Клиенты'),
        ),
    ]
