# Generated by Django 4.2.4 on 2023-08-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_remove_sender_customer_alter_sender_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='customer',
        ),
        migrations.AddField(
            model_name='sender',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.customer', verbose_name='Клиенты'),
        ),
    ]
