# Generated by Django 4.2.4 on 2023-08-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_remove_sender_customer_alter_sender_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='completion_time',
        ),
    ]
