# Generated by Django 4.2.4 on 2023-08-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_remove_sender_completion_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('attempt_status', models.CharField(choices=[('success', 'успешно'), ('failure', 'провал')], verbose_name='Статус попытки')),
                ('server_respond', models.CharField(verbose_name='Ответ сервера')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.sender', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
